services:
  mosquitto:
    image: eclipse-mosquitto:2.0.20
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  
  game-controller:
    container_name: game-controller
    build:
      context: ./game-controller
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mosquitto

